JSONArray Class Reference
#include <json.hpp>
Public Member Functions
JSONArray (std::string=`[]`)
JSONObject operator[] (int n)
template<typename T >
void set (int, T)
template<>
void set (int n, JSON t)
template<>
void set (int key, JSONObject value)
template<>
void set (int key, JSONArray value)
Additional Inherited Members
Detailed Description
Klasse für den Arbeit mit JSONArrays, ein Child von JSON
Definition at line 36 of file json.hpp.
Constructor & Destructor Documentation
JSONArray()
JSONArray::JSONArray (std::string content = `[]`) [inline]
Konstruktor für die Klasse JSONArray. Ladet den content ein.
Definition at line 152 of file json.hpp.
                                              : JSON(content)
{}
Member Function Documentation
operator[]()
JSONObject JSONArray::operator[] (int n) [inline]
Gibt den Wert beim Platz n zurück.
Definition at line 158 of file json.hpp.
References JSON::content, and json::JSON::Load().
{
    json::JSON obj = json::JSON::Load(content);
    JSONObject json(obj[n].dump());
    return json;
}
set() [1/4]
template<typename T >
void JSONArray::set (int n, T t) [inline]
Einstellen den Wert beim Platz n. Der neue Wert wird t sein (Template).
Definition at line 168 of file json.hpp.
References JSON::content, json::JSON::dump(), and json::JSON::Load().
{
        json::JSON obj = json::JSON::Load(content);
        obj[n] = t;
        content = obj.dump();
}
set() [2/4]
template<>
void JSONArray::set (int n, JSON t) [inline]
Einstellen den Wert beim Platz n. Der neue Wert wird t sein (JSON).
Definition at line 179 of file json.hpp.
References json::JSON::dump(), and json::JSON::Load().
{
        json::JSON obj = json::JSON::Load(content);
        json::JSON obj2 = json::JSON::Load((std::string)t);
        obj[n] = obj2;
        content = obj.dump();
}
set() [3/4]
template<>
void JSONArray::set (int key, JSONObject value) [inline]
Einstellen den Wert beim Platz n. Der neue Wert wird t sein (JSONObject).
Definition at line 191 of file json.hpp.
{
    (*this).set(key, dynamic_cast<JSON&>(value));
}
set() [4/4]
template<>
void JSONArray::set (int key, JSONArray value) [inline]
Einstellen den Wert beim Platz n. Der neue Wert wird t sein (JSONArray).
Definition at line 199 of file json.hpp.
{
    (*this).set(key, dynamic_cast<JSON&>(value));
}
The documentation for this class was generated from the following file:
src/json/json.hpp