json::JSON Class Reference
#include <json.hpp>
Data Structures
union BackingData
class JSONConstWrapper
class JSONWrapper
Public Types
enum Class {
Class::Null,
Class::Object,
Class::Array,
Class::String,
Class::Floating,
Class::Integral,
Class::Boolean
 }
Public Member Functions
JSON ()
JSON (initializer_list< JSON > list)
JSON (JSON &&other)
JSON & operator= (JSON &&other)
JSON (const JSON &other)
JSON & operator= (const JSON &other)
~JSON ()
template<typename T >
JSON (T b, typename enable_if< is_same< T, bool >::value >::type *=0)
template<typename T >
JSON (T i, typename enable_if< is_integral< T >::value &&!is_same< T, bool >::value >::type *=0)
template<typename T >
JSON (T f, typename enable_if< is_floating_point< T >::value >::type *=0)
template<typename T >
JSON (T s, typename enable_if< is_convertible< T, string >::value >::type *=0)
JSON (std::nullptr_t)
template<typename T >
void append (T arg)
template<typename T , typename... U>
void append (T arg, U... args)
template<typename T >
enable_if< is_same< T, bool >::value, JSON & >::type operator= (T b)
template<typename T >
enable_if< is_integral< T >::value &&!is_same< T, bool >::value, JSON & >::type operator= (T i)
template<typename T >
enable_if< is_floating_point< T >::value, JSON & >::type operator= (T f)
template<typename T >
enable_if< is_convertible< T, string >::value, JSON & >::type operator= (T s)
JSON & operator[] (const string &key)
JSON & operator[] (unsigned index)
JSON & at (const string &key)
const JSON & at (const string &key) const
JSON & at (unsigned index)
const JSON & at (unsigned index) const
int length () const
bool hasKey (const string &key) const
int size () const
Class JSONType () const
bool IsNull () const
Functions for getting primitives from the JSON object.
string ToString () const
string ToString (bool &ok) const
double ToFloat () const
double ToFloat (bool &ok) const
long ToInt () const
long ToInt (bool &ok) const
bool ToBool () const
bool ToBool (bool &ok) const
JSONWrapper< map< string, JSON > > ObjectRange ()
JSONWrapper< deque< JSON > > ArrayRange ()
JSONConstWrapper< map< string, JSON > > ObjectRange () const
JSONConstWrapper< deque< JSON > > ArrayRange () const
string dump (int depth=1, string tab=` `) const
Static Public Member Functions
static JSON Make (Class type)
static JSON Load (const string &)
Private Member Functions
void SetType (Class type)
void ClearInternal ()
Private Attributes
union json::JSON::BackingData Internal
Class Type = Class::Null
Friends
std::ostream & operator<< (std::ostream &, const JSON &)
Detailed Description
Definition at line 45 of file json.hpp.
Member Enumeration Documentation
Class
enum json::JSON::Class [strong]
Enumerator
Null
Object
Array
String
Floating
Integral
Boolean
Definition at line 63 of file json.hpp.
                         {
            Null,
            Object,
            Array,
            String,
            Floating,
            Integral,
            Boolean
        };
Constructor & Destructor Documentation
JSON() [1/9]
json::JSON::JSON () [inline]
Definition at line 99 of file json.hpp.
: Internal(), Type(Class::Null){}
JSON() [2/9]
json::JSON::JSON (initializer_list< JSON > list) [inline]
Definition at line 101 of file json.hpp.
References Object, and SetType().
            : JSON()
        {
            SetType(Class::Object);
            for(auto i = list.begin(), e = list.end(); i != e; ++i, ++i)
                operator[](i->ToString()) = *std::next(i);
        }
JSON() [3/9]
json::JSON::JSON (JSON && other) [inline]
Definition at line 109 of file json.hpp.
References Null.
            : Internal(other.Internal)
            , Type(other.Type)
        { other.Type = Class::Null; other.Internal.Map = nullptr; }
JSON() [4/9]
json::JSON::JSON (const JSON & other) [inline]
Definition at line 123 of file json.hpp.
References Array, Internal, json::JSON::BackingData::List, json::JSON::BackingData::Map, Object, json::JSON::BackingData::String, String, and Type.
                                  {
            switch(other.Type) {
            case Class::Object:
                Internal.Map =
                    new map<string,JSON>(other.Internal.Map->begin(),
                                          other.Internal.Map->end());
                break;
            case Class::Array:
                Internal.List =
                    new deque<JSON>(other.Internal.List->begin(),
                                      other.Internal.List->end());
                break;
            case Class::String:
                Internal.String =
                    new string(*other.Internal.String);
                break;
            default:
                Internal = other.Internal;
            }
            Type = other.Type;
        }
 JSON()
json::JSON::~JSON () [inline]
Definition at line 169 of file json.hpp.
References Array, Internal, json::JSON::BackingData::List, json::JSON::BackingData::Map, Object, json::JSON::BackingData::String, String, and Type.
                {
            switch(Type) {
            case Class::Array:
                delete Internal.List;
                break;
            case Class::Object:
                delete Internal.Map;
                break;
            case Class::String:
                delete Internal.String;
                break;
            default:;
            }
        }
JSON() [5/9]
template<typename T >
json::JSON::JSON (T b, typename enable_if< is_same< T, bool >::value >::type * = 0) [inline]
Definition at line 185 of file json.hpp.
: Internal(b), Type(Class::Boolean){}
JSON() [6/9]
template<typename T >
json::JSON::JSON (T i, typename enable_if< is_integral< T >::value &&!is_same< T, bool >::value >::type * = 0) [inline]
Definition at line 188 of file json.hpp.
: Internal((long)i), Type(Class::Integral){}
JSON() [7/9]
template<typename T >
json::JSON::JSON (T f, typename enable_if< is_floating_point< T >::value >::type * = 0) [inline]
Definition at line 191 of file json.hpp.
: Internal((double)f), Type(Class::Floating){}
JSON() [8/9]
template<typename T >
json::JSON::JSON (T s, typename enable_if< is_convertible< T, string >::value >::type * = 0) [inline]
Definition at line 194 of file json.hpp.
: Internal(string(s)), Type(Class::String){}
JSON() [9/9]
json::JSON::JSON (std::nullptr_t) [inline]
Definition at line 196 of file json.hpp.
: Internal(), Type(Class::Null){}
Member Function Documentation
append() [1/2]
template<typename T >
void json::JSON::append (T arg) [inline]
Definition at line 206 of file json.hpp.
References Array, Internal, json::JSON::BackingData::List, and SetType().
Referenced by append(), and json::Array().
                             {
            SetType(Class::Array); Internal.List->emplace_back(arg);
        }
append() [2/2]
template<typename T , typename... U>
void json::JSON::append (T arg, U... args) [inline]
Definition at line 211 of file json.hpp.
References append().
                                        {
            append(arg); append(args...);
        }
ArrayRange() [1/2]
JSONWrapper<deque<JSON> > json::JSON::ArrayRange () [inline]
Definition at line 318 of file json.hpp.
References Array, Internal, json::JSON::BackingData::List, and Type.
                                              {
            if(Type == Class::Array)
                return JSONWrapper<deque<JSON>>(Internal.List);
            return JSONWrapper<deque<JSON>>(nullptr);
        }
ArrayRange() [2/2]
JSONConstWrapper<deque<JSON> > json::JSON::ArrayRange () const [inline]
Definition at line 331 of file json.hpp.
References Array, Internal, json::JSON::BackingData::List, and Type.
                                                         {
            if(Type == Class::Array)
                return JSONConstWrapper<deque<JSON>>(Internal.List);
            return JSONConstWrapper<deque<JSON>>(nullptr);
        }
at() [1/4]
JSON& json::JSON::at (const string & key) [inline]
Definition at line 245 of file json.hpp.
References operator[]().
                                      {
            return operator[](key);
        }
at() [2/4]
const JSON& json::JSON::at (const string & key) const [inline]
Definition at line 249 of file json.hpp.
References Internal, and json::JSON::BackingData::Map.
                                                  {
            return Internal.Map->at(key);
        }
at() [3/4]
JSON& json::JSON::at (unsigned index) [inline]
Definition at line 253 of file json.hpp.
References operator[]().
                                   {
            return operator[](index);
        }
at() [4/4]
const JSON& json::JSON::at (unsigned index) const [inline]
Definition at line 257 of file json.hpp.
References Internal, and json::JSON::BackingData::List.
                                               {
            return Internal.List->at(index);
        }
ClearInternal()
void json::JSON::ClearInternal () [inline], [private]
Definition at line 407 of file json.hpp.
References Array, Internal, json::JSON::BackingData::List, json::JSON::BackingData::Map, Object, json::JSON::BackingData::String, String, and Type.
Referenced by operator=(), and SetType().
                           {
        switch(Type) {
          case Class::Object: delete Internal.Map; break;
          case Class::Array: delete Internal.List; break;
          case Class::String: delete Internal.String; break;
          default:;
        }
      }
dump()
string json::JSON::dump (int depth = 1, string tab = ` `) const [inline]
Definition at line 337 of file json.hpp.
References Array, json::JSON::BackingData::Bool, Boolean, json::JSON::BackingData::Float, Floating, json::JSON::BackingData::Int, Integral, Internal, json::anonymous_namespace{json.hpp}::json_escape(), json::JSON::BackingData::List, json::JSON::BackingData::Map, Null, Object, json::JSON::BackingData::String, String, and Type.
Referenced by JSONObject::put(), and JSONArray::set().
                                                             {
            string pad = "";
            for(int i = 0; i < depth; ++i, pad += tab);
            switch(Type) {
                case Class::Null:
                    return "null";
                case Class::Object: {
                    string s = "{\n";
                    bool skip = true;
                    for(auto &p : *Internal.Map) {
                        if(!skip) s += ",\n";
                        s += (pad + "" + p.first + " : " + p.second.dump(depth + 1, tab));
                        skip = false;
                    }
                    s += ("\n" + pad.erase(0, 2) + "}") ;
                    return s;
                }
                case Class::Array: {
                    string s = "[";
                    bool skip = true;
                    for(auto &p : *Internal.List) {
                        if(!skip) s += ", ";
                        s += p.dump(depth + 1, tab);
                        skip = false;
                    }
                    s += "]";
                    return s;
                }
                case Class::String:
                    return "" + json_escape(*Internal.String) + "";
                case Class::Floating:
                    return std::to_string(Internal.Float);
                case Class::Integral:
                    return std::to_string(Internal.Int);
                case Class::Boolean:
                    return Internal.Bool ? "true" : "false";
                default:
                    return "";
            }
            return "";
        }
hasKey()
bool json::JSON::hasKey (const string & key) const [inline]
Definition at line 268 of file json.hpp.
References Internal, json::JSON::BackingData::Map, Object, and Type.
                                               {
            if(Type == Class::Object)
                return Internal.Map->find(key) != Internal.
      Map->end();
            return false;
        }
IsNull()
bool json::JSON::IsNull () const [inline]
Functions for getting primitives from the JSON object.
Definition at line 286 of file json.hpp.
References Null, and Type.
{ return Type == Class::Null; }
JSONType()
Class json::JSON::JSONType () const [inline]
Definition at line 283 of file json.hpp.
References Type.
{ return Type; }
length()
int json::JSON::length () const [inline]
Definition at line 261 of file json.hpp.
References Array, Internal, json::JSON::BackingData::List, and Type.
                           {
            if(Type == Class::Array)
                return Internal.List->size();
            else
                return -1;
        }
Load()
JSON JSON::Load (const string & str) [inline], [static]
Definition at line 644 of file json.hpp.
References json::anonymous_namespace{json.hpp}::parse_next().
Referenced by JSONObject::get(), JSONArray::operator[](), JSONObject::put(), and JSONArray::set().
                                          {
    size_t offset = 0;
    return std::move(parse_next(str, offset));
}
Make()
static JSON json::JSON::Make (Class type) [inline], [static]
Definition at line 198 of file json.hpp.
References SetType().
Referenced by json::Array(), json::Object(), json::anonymous_namespace{json.hpp}::parse_array(), json::anonymous_namespace{json.hpp}::parse_bool(), json::anonymous_namespace{json.hpp}::parse_null(), json::anonymous_namespace{json.hpp}::parse_number(), json::anonymous_namespace{json.hpp}::parse_object(), and json::anonymous_namespace{json.hpp}::parse_string().
                                       {
            JSON ret; ret.SetType(type);
            return ret;
        }
ObjectRange() [1/2]
JSONWrapper<map<string,JSON> > json::JSON::ObjectRange () [inline]
Definition at line 312 of file json.hpp.
References Internal, json::JSON::BackingData::Map, Object, and Type.
                                                    {
            if(Type == Class::Object)
                return JSONWrapper<map<string,JSON>>(Internal.Map);
            return JSONWrapper<map<string,JSON>>(nullptr);
        }
ObjectRange() [2/2]
JSONConstWrapper<map<string,JSON> > json::JSON::ObjectRange () const [inline]
Definition at line 324 of file json.hpp.
References Internal, json::JSON::BackingData::Map, Object, and Type.
                                                               {
            if(Type == Class::Object)
                return JSONConstWrapper<map<string,JSON>>(Internal.Map);
            return JSONConstWrapper<map<string,JSON>>(nullptr);
        }
operator=() [1/6]
JSON& json::JSON::operator= (JSON && other) [inline]
Definition at line 114 of file json.hpp.
References ClearInternal(), Internal, Null, and Type.
                                        {
            ClearInternal();
            Internal = other.Internal;
            Type = other.Type;
            other.Internal.Map = nullptr;
            other.Type = Class::Null;
            return *this;
        }
operator=() [2/6]
JSON& json::JSON::operator= (const JSON & other) [inline]
Definition at line 145 of file json.hpp.
References Array, ClearInternal(), Internal, json::JSON::BackingData::List, json::JSON::BackingData::Map, Object, json::JSON::BackingData::String, String, and Type.
                                             {
            ClearInternal();
            switch(other.Type) {
            case Class::Object:
                Internal.Map =
                    new map<string,JSON>(other.Internal.Map->begin(),
                                          other.Internal.Map->end());
                break;
            case Class::Array:
                Internal.List =
                    new deque<JSON>(other.Internal.List->begin(),
                                      other.Internal.List->end());
                break;
            case Class::String:
                Internal.String =
                    new string(*other.Internal.String);
                break;
            default:
                Internal = other.Internal;
            }
            Type = other.Type;
            return *this;
        }
operator=() [3/6]
template<typename T >
enable_if<is_same<T,bool>::value, JSON&>::type json::JSON::operator= (T b) [inline]
Definition at line 216 of file json.hpp.
References json::JSON::BackingData::Bool, Boolean, Internal, and SetType().
                                                                                 {
                SetType(Class::Boolean); Internal.
      Bool = b; return *this;
            }
operator=() [4/6]
template<typename T >
enable_if<is_integral<T>::value && !is_same<T,bool>::value, JSON&>::type json::JSON::operator= (T i) [inline]
Definition at line 221 of file json.hpp.
References json::JSON::BackingData::Int, Integral, Internal, and SetType().
                                                                                                         {
                SetType(Class::Integral); Internal.
      Int = i; return *this;
            }
operator=() [5/6]
template<typename T >
enable_if<is_floating_point<T>::value, JSON&>::type json::JSON::operator= (T f) [inline]
Definition at line 226 of file json.hpp.
References json::JSON::BackingData::Float, Floating, Internal, and SetType().
                                                                                      {
                SetType(Class::Floating); Internal.
      Float = f; return *this;
            }
operator=() [6/6]
template<typename T >
enable_if<is_convertible<T,string>::value, JSON&>::type json::JSON::operator= (T s) [inline]
Definition at line 231 of file json.hpp.
References Internal, SetType(), json::JSON::BackingData::String, and String.
                                                                                          {
                SetType(Class::String); *Internal.
      String = string(s); return *this;
            }
operator[]() [1/2]
JSON& json::JSON::operator[] (const string & key) [inline]
Definition at line 235 of file json.hpp.
References Internal, json::JSON::BackingData::Map, Object, and SetType().
Referenced by at().
                                              {
            SetType(Class::Object); return Internal.
      Map->operator[](key);
        }
operator[]() [2/2]
JSON& json::JSON::operator[] (unsigned index) [inline]
Definition at line 239 of file json.hpp.
References Array, Internal, json::JSON::BackingData::List, and SetType().
                                           {
            SetType(Class::Array);
            if(index >= Internal.List->size()) Internal.
      List->resize(index + 1);
            return Internal.List->operator[](index);
        }
SetType()
void json::JSON::SetType (Class type) [inline], [private]
Definition at line 383 of file json.hpp.
References Array, json::JSON::BackingData::Bool, Boolean, ClearInternal(), json::JSON::BackingData::Float, Floating, json::JSON::BackingData::Int, Integral, Internal, json::JSON::BackingData::List, json::JSON::BackingData::Map, Null, Object, json::JSON::BackingData::String, String, and Type.
Referenced by append(), JSON(), Make(), operator=(), and operator[]().
                                   {
            if(type == Type)
                return;
            ClearInternal();
          
            switch(type) {
            case Class::Null: Internal.Map = nullptr; break;
            case Class::Object: Internal.Map = new map<string,JSON>(); break;
            case Class::Array: Internal.List = new deque<JSON>(); break;
            case Class::String: Internal.String = new string();
      break;
            case Class::Floating: Internal.Float = 0.0;
      break;
            case Class::Integral: Internal.Int = 0;
      break;
            case Class::Boolean: Internal.Bool = false;
      break;
            }
            Type = type;
        }
size()
int json::JSON::size () const [inline]
Definition at line 274 of file json.hpp.
References Array, Internal, json::JSON::BackingData::List, json::JSON::BackingData::Map, Object, and Type.
                         {
            if(Type == Class::Object)
                return Internal.Map->size();
            else if(Type == Class::Array)
                return Internal.List->size();
            else
                return -1;
        }
ToBool() [1/2]
bool json::JSON::ToBool () const [inline]
Definition at line 306 of file json.hpp.
References ToBool().
Referenced by json::anonymous_namespace{json.hpp}::parse_bool(), and ToBool().
{ bool b; return ToBool(b); }
ToBool() [2/2]
bool json::JSON::ToBool (bool & ok) const [inline]
Definition at line 307 of file json.hpp.
References json::JSON::BackingData::Bool, Boolean, Internal, and Type.
                                      {
            ok = (Type == Class::Boolean);
            return ok ? Internal.Bool : false;
        }
ToFloat() [1/2]
double json::JSON::ToFloat () const [inline]
Definition at line 294 of file json.hpp.
References ToFloat().
Referenced by ToFloat().
{ bool b; return ToFloat(b); }
ToFloat() [2/2]
double json::JSON::ToFloat (bool & ok) const [inline]
Definition at line 295 of file json.hpp.
References json::JSON::BackingData::Float, Floating, Internal, and Type.
                                         {
            ok = (Type == Class::Floating);
            return ok ? Internal.Float : 0.0;
        }
ToInt() [1/2]
long json::JSON::ToInt () const [inline]
Definition at line 300 of file json.hpp.
References ToInt().
Referenced by ToInt().
{ bool b; return ToInt(b); }
ToInt() [2/2]
long json::JSON::ToInt (bool & ok) const [inline]
Definition at line 301 of file json.hpp.
References json::JSON::BackingData::Int, Integral, Internal, and Type.
                                     {
            ok = (Type == Class::Integral);
            return ok ? Internal.Int : 0;
        }
ToString() [1/2]
string json::JSON::ToString () const [inline]
Definition at line 288 of file json.hpp.
References ToString().
Referenced by json::anonymous_namespace{json.hpp}::parse_object(), and ToString().
{ bool b; return std::move(ToString(b)); }
ToString() [2/2]
string json::JSON::ToString (bool & ok) const [inline]
Definition at line 289 of file json.hpp.
References Internal, json::anonymous_namespace{json.hpp}::json_escape(), json::JSON::BackingData::String, String, and Type.
                                          {
            ok = (Type == Class::String);
            return ok ? std::move(json_escape(*Internal.
      String)): string("");
        }
Friends And Related Function Documentation
operator<<
std::ostream& operator<< (std::ostream & os, const JSON & json) [friend]
Definition at line 436 of file json.hpp.
                                                                  {
    os << json.dump();
    return os;
}
Field Documentation
Internal
union json::JSON::BackingData json::JSON::Internal [private]
Referenced by append(), ArrayRange(), at(), ClearInternal(), dump(), hasKey(), JSON(), length(), ObjectRange(), operator=(), operator[](), SetType(), size(), ToBool(), ToFloat(), ToInt(), ToString(), and ~JSON().
Type
Class json::JSON::Type = Class::Null [private]
Definition at line 418 of file json.hpp.
Referenced by ArrayRange(), ClearInternal(), dump(), hasKey(), IsNull(), JSON(), JSONType(), length(), ObjectRange(), operator=(), SetType(), size(), ToBool(), ToFloat(), ToInt(), ToString(), and ~JSON().
The documentation for this class was generated from the following file:
lib/simplejson/json.hpp