JSONObject Class Reference
#include <json.hpp>
Public Member Functions
JSONObject (std::string=`{}`)
JSONObject get (std::string)
template<typename T >
void put (std::string, T)
operator int ()
JSONArray & toArr ()
JSONObject operator[] (int)
template<>
void put (std::string key, JSON value)
template<>
void put (std::string key, JSONObject value)
template<>
void put (std::string key, JSONArray value)
Additional Inherited Members
Detailed Description
Klasse für den Arbeit mit JSONObjects, ein Child von JSON
Definition at line 48 of file json.hpp.
Constructor & Destructor Documentation
JSONObject()
JSONObject::JSONObject (std::string content = `{}`) [inline]
Konstruktor des JSONObjectes, ladet den inhalt ein.
Definition at line 88 of file json.hpp.
                                               : JSON(content)
{}
Member Function Documentation
get()
JSONObject JSONObject::get (std::string key) [inline]
Gibt den Wert mit Schlüssel key zurück als eine neue JSONObject.
Definition at line 94 of file json.hpp.
References JSON::content, and json::JSON::Load().
{
    json::JSON obj = json::JSON::Load(content);
    JSONObject json(obj[key].dump());
    return json;
}
operator int()
JSONObject::operator int () [inline]
Gibt den Wert des Objektes als ein Integer zurück.
Definition at line 82 of file json.hpp.
{return atoi(content.c_str());}
operator[]()
JSONObject JSONObject::operator[] (int)
put() [1/4]
template<typename T >
void JSONObject::put (std::string key, T value) [inline]
Ein neues Wert zum JSON Dateien einfügen mit Schlüssel key und Wert value. Diese Methode funktioniert für fast alle Werte (deswegen eine Template wird benutzt).
Definition at line 113 of file json.hpp.
References JSON::content, json::JSON::dump(), and json::JSON::Load().
{
    json::JSON obj = json::JSON::Load(content);
    obj[key] = value;
    content = obj.dump();
}
put() [2/4]
template<>
void JSONObject::put (std::string key, JSON value) [inline]
Ein neues Wert zum JSON Dateien einfügen mit Schlüssel key und Wert value. Diese Methode funktioniert nur für Werte mit JSON-Typ.
Definition at line 123 of file json.hpp.
References json::JSON::dump(), and json::JSON::Load().
{
    json::JSON obj = json::JSON::Load(content);
    json::JSON obj2 = json::JSON::Load((std::string)value);
    obj[key] = obj2;
    content = obj.dump();
}
put() [3/4]
template<>
void JSONObject::put (std::string key, JSONObject value) [inline]
Ein neues Wert zum JSON Dateien einfügen mit Schlüssel key und Wert value. Diese Methode funktioniert nur für JSONObjects.
Definition at line 135 of file json.hpp.
{
    (*this).put(key, dynamic_cast<JSON&>(value));
}
put() [4/4]
template<>
void JSONObject::put (std::string key, JSONArray value) [inline]
Ein neues Wert zum JSON Dateien einfügen mit Schlüssel key und Wert value. Diese Methode funktioniert nur für JSONArrays.
Definition at line 143 of file json.hpp.
{
    (*this).put(key, dynamic_cast<JSON&>(value));
}
toArr()
JSONArray & JSONObject::toArr () [inline]
Falls die JSONObject eine Array enthalten soll, muss man kastieren.
Definition at line 104 of file json.hpp.
{
    return *static_cast<JSONArray*>(static_cast<JSON*>(this));
}
The documentation for this class was generated from the following file:
src/json/json.hpp