Datei Class Reference
#include <datei.hpp>
Public Member Functions
Datei (std::string)
virtual std::string print ()=0
std::string getLang ()
Protected Attributes
std::string language
Friends
std::ostream & operator<< (std::ostream &, Datei &)
Detailed Description
Klasse für Dateien.
Definition at line 10 of file datei.hpp.
Constructor & Destructor Documentation
Datei()
Datei::Datei (std::string lang)
Konstruktor für Dateien, stellt die Sprache ein.
Definition at line 7 of file datei.cpp.
: language(lang) {}
Member Function Documentation
getLang()
std::string Datei::getLang ()
Getterfunktion für die Sprache.
Definition at line 22 of file datei.cpp.
References language.
Referenced by VirtualMachine::addSubroutine(), VirtualMachine::runInstruction(), and VirtualMachine::VirtualMachine().
{ return language;}
print()
virtual std::string Datei::print () [pure virtual]
Implemented in ComplexInstruktion, SimpleInstruktion, Sprache, and Instruktion.
Referenced by operator<<().
Friends And Related Function Documentation
operator<<
std::ostream& operator<< (std::ostream & os, Datei & d) [friend]
Auschreiben.
Definition at line 13 of file datei.cpp.
{
    os<<d.print();
    return os;
}
Field Documentation
language
std::string Datei::language [protected]
Definition at line 12 of file datei.hpp.
Referenced by getLang().
The documentation for this class was generated from the following files:
src/datei/datei.hpp
src/datei/datei.cpp