Memory Class Reference
#include <memory.hpp>
Public Member Functions
const unsigned int getSize ()
Memory (unsigned int)
~Memory ()
Memory (const Memory &)
bool write (unsigned int, uint8_t)
uint8_t & read (unsigned int)
bool shiftRight (unsigned int, uint8_t, uint8_t, uint8_t &, uint8_t)
bool shiftLeft (unsigned int, uint8_t, uint8_t, uint8_t &, uint8_t)
Private Attributes
uint8_t * speicherBereich
const unsigned int size
Detailed Description
Klasse für die Darstellung des Speicherplatzes.
Definition at line 11 of file memory.hpp.
Constructor & Destructor Documentation
Memory() [1/2]
Memory::Memory (unsigned int n)
Konstruktor des Speicherplatzes.
Definition at line 7 of file memory.cpp.
References speicherBereich.
                             : size(n)
{
    speicherBereich = new uint8_t[n];
}
 Memory()
Memory::~Memory ()
Destruktor des Speicherplatzes..
Definition at line 25 of file memory.cpp.
References speicherBereich.
{
    delete [] speicherBereich;
}
Memory() [2/2]
Memory::Memory (const Memory & obj)
Kopierkonstruktor des Speicherplatzes.
Definition at line 15 of file memory.cpp.
References size, and speicherBereich.
                                : size(obj.size)
{
    speicherBereich = new uint8_t[size];
    memcpy(speicherBereich, obj.speicherBereich,
      size);
}
Member Function Documentation
getSize()
const unsigned int Memory::getSize ()
Definition at line 31 of file memory.cpp.
References size.
Referenced by VirtualMachine::getReference(), and VirtualMachine::getValue().
{
    return size;
}
read()
uint8_t & Memory::read (unsigned int address)
Gibt den Wert beim address zurück.
Definition at line 51 of file memory.cpp.
References speicherBereich.
Referenced by VirtualMachine::getReference(), and VirtualMachine::getValue().
{
    return speicherBereich[address];
}
shiftLeft()
bool Memory::shiftLeft (unsigned int address, uint8_t data, uint8_t dataMask, uint8_t & flag, uint8_t mask)
Verschiebt den Wert beim address nach links.
Definition at line 73 of file memory.cpp.
References size, speicherBereich, and write().
{
    if(address >= size) return false;
    uint8_t newdata = ((data & dataMask) && 1) | ((speicherBereich[address] & 0x7F) << 1);
    flag &= ~mask;
    flag |= ((speicherBereich[address] & 0x80)) ? mask : 0;
    return this->write(address, newdata);
    
}
shiftRight()
bool Memory::shiftRight (unsigned int address, uint8_t data, uint8_t dataMask, uint8_t & flag, uint8_t mask)
Verschiebt den Wert beim address nach rechts.
Definition at line 59 of file memory.cpp.
References size, speicherBereich, and write().
{
    if(address >= size) return false;
    uint8_t newdata = ((data & dataMask)&&1)<<7 | ((speicherBereich[address] & 0xFE) >> 1);
    flag&= ~mask;
    flag |= (speicherBereich[address] & 0x01) ? mask : 0;
    return this->write(address, newdata);
}
write()
bool Memory::write (unsigned int address, uint8_t data)
Schreibt data in dem Speicher beim address ein.
Definition at line 39 of file memory.cpp.
References size, and speicherBereich.
Referenced by shiftLeft(), and shiftRight().
{
    if(address >= size) return false;
    speicherBereich[address] = data;
    return true;
}
Field Documentation
size
const unsigned int Memory::size [private]
Definition at line 14 of file memory.hpp.
Referenced by getSize(), Memory(), shiftLeft(), shiftRight(), and write().
speicherBereich
uint8_t* Memory::speicherBereich [private]
Definition at line 13 of file memory.hpp.
Referenced by Memory(), read(), shiftLeft(), shiftRight(), write(), and ~Memory().
The documentation for this class was generated from the following files:
src/memory/memory.hpp
src/memory/memory.cpp