VirtualMachine Class Reference
#include <virtualmachine.hpp>
Public Member Functions
VirtualMachine (Sprache, unsigned int=1024, unsigned int=16)
bool runInstruction (std::string)
void reRunAll ()
bool addSubroutine (std::string)
uint8_t & getReference (std::string)
uint8_t getValue (std::string)
void runSubroutine (std::string)
void pushValue (uint8_t)
uint8_t popValue ()
Private Member Functions
void * getPtr (std::string)
Private Attributes
std::stack< uint8_t > stack
Memory memory
Memory generalRegisterArray
Memory specialRegisterArray
std::map< std::string, ComplexInstruktion * > labels
std::map< std::string, ComplexInstruktion * > subroutines
Sprache language
std::map< std::string, void * > functions
Detailed Description
Klasse für den virtuellen Gerät, wodurch die Instruktionen ausgeführt werden können.
Definition at line 18 of file virtualmachine.hpp.
Constructor & Destructor Documentation
VirtualMachine()
VirtualMachine::VirtualMachine (Sprache sprache, unsigned int memory = 1024, unsigned int general = 16)
Konstruktor der Klasse VirtualMachine..
Definition at line 170 of file virtualmachine.cpp.
References add(), functions, Datei::getLang(), jsr(), language, Sprache::languageElements, mov(), pop(), push(), sl0(), sr0(), sub(), subroutines, and swp().
                                                                                         :
      memory(memory), generalRegisterArray(general),
      specialRegisterArray(2), language(sprache)
{
    std::vector<std::string>::iterator i = sprache.languageElements.begin();
    functions.insert(std::make_pair(*(i++), (void*)mov));
    functions.insert(std::make_pair(*(i++), (void*)add));
    functions.insert(std::make_pair(*(i++), (void*)sub));
    functions.insert(std::make_pair(*(i++), (void*)swp));
    functions.insert(std::make_pair(*(i++), (void*)sl0));
    functions.insert(std::make_pair(*(i++), (void*)sr0));
    functions.insert(std::make_pair(*(i++), (void*)jsr));
    functions.insert(std::make_pair(*(i++), (void*)push));
    functions.insert(std::make_pair(*(i++), (void*)pop));
    
    subroutines.insert(std::make_pair("_start",(new
      ComplexInstruktion(language.getLang()))));
}
Member Function Documentation
addSubroutine()
bool VirtualMachine::addSubroutine (std::string s)
Addieren eine Subroutine
Definition at line 262 of file virtualmachine.cpp.
References ComplexInstruktion::add(), Datei::getLang(), getPtr(), language, and subroutines.
Referenced by main().
{
    std::istringstream iss(s);
    std::string buff;
    ComplexInstruktion *ci = new ComplexInstruktion(
      language.getLang());
    std::getline(iss, buff);
    subroutines.insert(std::make_pair(buff, ci));
    while (std::getline(iss, buff)) {
        std::istringstream is(buff);
        std::string instruction, param1, param2;
        is>>instruction;
        is>>param1;
        is>>param2;
        SimpleInstruktion *sNew = new SimpleInstruktion(
      language.getLang(), buff, getPtr(instruction), param1, param2);
        ci->add(*sNew);
    }
}
getPtr()
void * VirtualMachine::getPtr (std::string s) [private]
Gibt den Funktionenpointer zum Befehl zurück..
Definition at line 190 of file virtualmachine.cpp.
References functions, Sprache::instructions, and language.
Referenced by addSubroutine(), and runInstruction().
{
    std::string str;
    for(auto pair : language.instructions)
    {
        if(pair.first == s)
        {
            str = pair.second;
            break;
        }
    }
    for(auto pair : functions)
    {
        if(pair.first == str)
        {
            return (pair.second);
        }
    }
}
getReference()
uint8_t & VirtualMachine::getReference (std::string s)
Gibt den Referenz des Wertes zurück (also es geändert werden kann).
Definition at line 108 of file virtualmachine.cpp.
References generalRegisterArray, Memory::getSize(), memory, and Memory::read().
Referenced by add(), mov(), pop(), sl0(), sr0(), sub(), and swp().
{
    unsigned int reg;
    std::stringstream ss;
    switch(s[0])
    {
        case '(':
            ss << s.substr(2, s.size()-1);
            ss >> reg;
            if(generalRegisterArray.read(reg) > (this->
      memory).getSize()) throw ("Memory is out of bounds. Please cross-check syntax!");
            return memory.read(generalRegisterArray.
      read(reg));
            break;
        case 'r':
            ss << s.substr(1, s.size());
            ss >> reg;
            if(reg > generalRegisterArray.getSize()) throw ("Register does not
       exist. Please cross-check syntax!");
            return generalRegisterArray.read(reg);
            break;
        default:
            throw ("Please cross-check syntax!");
            break;
    }
}
getValue()
uint8_t VirtualMachine::getValue (std::string s)
Gibt den Wert zurück (nicht veränderbar).
Definition at line 136 of file virtualmachine.cpp.
References generalRegisterArray, Memory::getSize(), memory, and Memory::read().
Referenced by add(), main(), mov(), push(), sl0(), sr0(), sub(), and swp().
{
    unsigned int reg;
    unsigned int ret;
    std::stringstream ss;
    std::istringstream iss(s);
    switch(s[0])
    {
        case '(':
            ss << s.substr(2, s.size()-1);
            ss >> reg;
            if(generalRegisterArray.read(reg) > (this->
      memory).getSize()) throw ("Memory is out of bounds. Please cross-check syntax!");
            return memory.read(generalRegisterArray.
      read(reg));
            break;
        case 'r':
            ss << s.substr(1, s.size());
            ss >> reg;
            if(reg > generalRegisterArray.getSize()) throw ("Register does not
       exist. Please cross-check syntax!");
            return generalRegisterArray.read(reg);
            break;
        case '0':
            iss >> std::hex >> ret;
            return ret;
        default:
            throw ("Please cross-check syntax!");
            break;
    }
}
popValue()
uint8_t VirtualMachine::popValue ()
Stackmanipulation.
Definition at line 81 of file virtualmachine.cpp.
References stack.
Referenced by pop().
{
    uint8_t t = stack.top();
    stack.pop();
    return t;
}
pushValue()
void VirtualMachine::pushValue (uint8_t t)
Stackmanipulation
Definition at line 73 of file virtualmachine.cpp.
References stack.
Referenced by push().
{
    stack.push(t);
}
reRunAll()
void VirtualMachine::reRunAll ()
Ausführen jede Instruktion nocheinmal.
Definition at line 246 of file virtualmachine.cpp.
References subroutines.
Referenced by main().
{
    for(auto pair : subroutines)
        {
            if(pair.first == "_start")
            {
                
                pair.second->run((*this));
            }
        }
}
runInstruction()
bool VirtualMachine::runInstruction (std::string r)
Parsen eine Instruktion aus einem String, zum VM history einfügen und danach laufen lassen
Definition at line 215 of file virtualmachine.cpp.
References Datei::getLang(), getPtr(), Sprache::instructions, language, and subroutines.
Referenced by main().
{
    std::istringstream is(r);
    std::string instruction, param1, param2;
    is>>instruction;
    bool is_ok = false;
    for(auto i : language.instructions)
    {
        if(i.first == instruction) is_ok = true;
    }
    if(!is_ok) throw ("Please cross-check spelling of the mnemonik!");
    is>>param1;
    is>>param2;
    SimpleInstruktion *sNew = new SimpleInstruktion(
      language.getLang(), r, getPtr(instruction), param1, param2);
    for(std::pair<std::string, ComplexInstruktion*> pair : subroutines)
    {
        if(pair.first == "_start")
        {
            pair.second->add(*sNew);
            break;
        }
    }
    sNew -> run(*this);
    return true;
}
runSubroutine()
void VirtualMachine::runSubroutine (std::string s)
Ausführt eine andere subroutine.
Definition at line 92 of file virtualmachine.cpp.
References subroutines.
Referenced by jsr().
{
    for(auto pair : subroutines)
    {
        if(pair.first == s)
        {
            
            pair.second->run((*this));
        }
    }
}
Field Documentation
functions
std::map<std::string, void*> VirtualMachine::functions [private]
Definition at line 28 of file virtualmachine.hpp.
Referenced by getPtr(), and VirtualMachine().
generalRegisterArray
Memory VirtualMachine::generalRegisterArray [private]
Definition at line 23 of file virtualmachine.hpp.
Referenced by getReference(), and getValue().
labels
std::map<std::string, ComplexInstruktion*> VirtualMachine::labels [private]
Definition at line 25 of file virtualmachine.hpp.
language
Sprache VirtualMachine::language [private]
Definition at line 27 of file virtualmachine.hpp.
Referenced by addSubroutine(), getPtr(), runInstruction(), and VirtualMachine().
memory
Memory VirtualMachine::memory [private]
Definition at line 22 of file virtualmachine.hpp.
Referenced by getReference(), and getValue().
specialRegisterArray
Memory VirtualMachine::specialRegisterArray [private]
Definition at line 24 of file virtualmachine.hpp.
stack
std::stack<uint8_t> VirtualMachine::stack [private]
Definition at line 21 of file virtualmachine.hpp.
Referenced by popValue(), and pushValue().
subroutines
std::map<std::string, ComplexInstruktion*> VirtualMachine::subroutines [private]
Definition at line 26 of file virtualmachine.hpp.
Referenced by addSubroutine(), reRunAll(), runInstruction(), runSubroutine(), and VirtualMachine().
The documentation for this class was generated from the following files:
src/virtualmachine/virtualmachine.hpp
src/virtualmachine/virtualmachine.cpp