json Namespace Reference
Namespaces
 anonymous_namespace{json.hpp}
Data Structures
class JSON
Functions
JSON Array ()
template<typename... T>
JSON Array (T... args)
JSON Object ()
std::ostream & operator<< (std::ostream &os, const JSON &json)
Function Documentation
Array() [1/2]
JSON json::Array () [inline]
Definition at line 421 of file json.hpp.
References json::JSON::Array, and json::JSON::Make().
Referenced by json::anonymous_namespace{json.hpp}::parse_array().
                    {
    return std::move(JSON::Make(JSON::Class::Array));
}
Array() [2/2]
template<typename... T>
JSON json::Array (T... args)
Definition at line 426 of file json.hpp.
References json::JSON::append(), json::JSON::Array, and json::JSON::Make().
                        {
    JSON arr = JSON::Make(JSON::Class::Array);
    arr.append(args...);
    return std::move(arr);
}
Object()
JSON json::Object () [inline]
Definition at line 432 of file json.hpp.
References json::JSON::Make(), and json::JSON::Object.
Referenced by json::anonymous_namespace{json.hpp}::parse_object().
                     {
    return std::move(JSON::Make(JSON::Class::Object));
}
operator<<()
std::ostream& json::operator<< (std::ostream & os, const JSON & json) [inline]
Definition at line 436 of file json.hpp.
                                                                  {
    os << json.dump();
    return os;
}