src/virtualmachine/virtualmachine.cpp File Reference
#include `virtualmachine.hpp`
#include <sstream>
Functions
void mov (VirtualMachine &vm, std::string s1, std::string s2)
void add (VirtualMachine &vm, std::string s1, std::string s2)
void sub (VirtualMachine &vm, std::string s1, std::string s2)
void swp (VirtualMachine &vm, std::string s1, std::string s2)
void sl0 (VirtualMachine &vm, std::string s1, std::string s2)
void sr0 (VirtualMachine &vm, std::string s1, std::string s2)
void jsr (VirtualMachine &vm, std::string s1, std::string s2)
void push (VirtualMachine &vm, std::string s1, std::string s2)
void pop (VirtualMachine &vm, std::string s1, std::string s2)
Function Documentation
add()
void add (VirtualMachine & vm, std::string s1, std::string s2)
Instruktiondefinition.
Definition at line 17 of file virtualmachine.cpp.
References VirtualMachine::getReference(), and VirtualMachine::getValue().
Referenced by VirtualMachine::VirtualMachine().
                                                        {
    vm.getReference(s1) = vm.getValue(s2) + vm.getValue(s1);
}
jsr()
void jsr (VirtualMachine & vm, std::string s1, std::string s2)
Instruktiondefinition.
Definition at line 52 of file virtualmachine.cpp.
References VirtualMachine::runSubroutine().
Referenced by VirtualMachine::VirtualMachine().
                                                        {
    vm.runSubroutine(s1);
}
mov()
void mov (VirtualMachine & vm, std::string s1, std::string s2)
Instruktiondefinition.
Definition at line 10 of file virtualmachine.cpp.
References VirtualMachine::getReference(), and VirtualMachine::getValue().
Referenced by VirtualMachine::VirtualMachine().
                                                        {
    vm.getReference(s1) = vm.getValue(s2);
}
pop()
void pop (VirtualMachine & vm, std::string s1, std::string s2)
Instruktiondefinition.
Definition at line 66 of file virtualmachine.cpp.
References VirtualMachine::getReference(), and VirtualMachine::popValue().
Referenced by VirtualMachine::VirtualMachine().
                                                        {
    vm.getReference(s1) = vm.popValue();
}
push()
void push (VirtualMachine & vm, std::string s1, std::string s2)
Instruktiondefinition.
Definition at line 59 of file virtualmachine.cpp.
References VirtualMachine::getValue(), and VirtualMachine::pushValue().
Referenced by VirtualMachine::VirtualMachine().
                                                         {
    vm.pushValue(vm.getValue(s1));
}
sl0()
void sl0 (VirtualMachine & vm, std::string s1, std::string s2)
Instruktiondefinition.
Definition at line 38 of file virtualmachine.cpp.
References VirtualMachine::getReference(), and VirtualMachine::getValue().
Referenced by VirtualMachine::VirtualMachine().
                                                        {
    vm.getReference(s1) = vm.getValue(s1) << 1;
}
sr0()
void sr0 (VirtualMachine & vm, std::string s1, std::string s2)
Instruktiondefinition.
Definition at line 45 of file virtualmachine.cpp.
References VirtualMachine::getReference(), and VirtualMachine::getValue().
Referenced by VirtualMachine::VirtualMachine().
                                                        {
    vm.getReference(s1) = vm.getValue(s1) >> 1;
}
sub()
void sub (VirtualMachine & vm, std::string s1, std::string s2)
Instruktiondefinition.
Definition at line 24 of file virtualmachine.cpp.
References VirtualMachine::getReference(), and VirtualMachine::getValue().
Referenced by VirtualMachine::VirtualMachine().
                                                        {
    vm.getReference(s1) = vm.getValue(s1) - vm.getValue(s2);
}
swp()
void swp (VirtualMachine & vm, std::string s1, std::string s2)
Instruktiondefinition.
Definition at line 31 of file virtualmachine.cpp.
References VirtualMachine::getReference(), and VirtualMachine::getValue().
Referenced by VirtualMachine::VirtualMachine().
                                                        {
    vm.getReference(s1) = (vm.getValue(s1)) >> 4 | (vm.
      getValue(s1) << 4);
}